# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            provider: db_provider

            #  http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true
                default_target_path: /
              # activate different ways to authenticate

            logout:
                path: /logout
                target: /

    access_control:
        # Rôle nécessaire pour accéder à la route /admin
        # - { path: ^/(specialty|user), roles: ROLE_ADMIN }
        # - { path: ^/.*/new, roles: ROLE_ADMIN }
        # - { path: ^/.*/[0-9]+/edit, roles: [ROLE_TEACHER, ROLE_STUDENT] }
        # # # Routes accessibles par le professeur
        # - { path: ^/(specialty|user)/[0-9]+, roles: [ROLE_TEACHER, ROLE_STUDENT] }
        # - { path: ^/(specialty|user), roles: ROLE_TEACHER }
        # # Routes accessibles par l'anonyme
        # - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    # role_hierarchy:
    #    ROLE_TEACHER : ROLE_STUDENT
    #    ROLE_ADMIN: ROLE_TEACHER
